In [9]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [10]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]

In [11]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [12]:
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [13]:
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [14]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>

# 1] Task 1¶
## [1.1] Logistic regression(SGDClassifier with logloss

In [15]:
"""
lr_clsfr: Logistic Rgression classifier
"""
lr_clsfr = linear_model.SGDClassifier(loss='log', eta0 = 0.0001, alpha = 0.0001, penalty = 'l2', random_state = 15, verbose = 2, n_jobs = -1 )


In [18]:
d_train = data[['f1', 'f2', 'f3']].values
print("1. Data Type of d_train: {}", [type(d_train)])
print("2. Shape of d_train: {}\n\n", [d_train.shape])

y = data[['y']].values
print("1. Data Type of y: {}", [type(y)])
print("2. Shape of y: ", [y.shape])

1. Data Type of d_train: {} [<class 'numpy.ndarray'>]
2. Shape of d_train: {}

 [(200, 3)]
1. Data Type of y: {} [<class 'numpy.ndarray'>]
2. Shape of y:  [(200, 1)]


In [19]:
"""
Let's reshape y dimension from 2-D array to vector
"""
y = y.reshape(-1)

In [20]:
lr_clsfr.fit(d_train, y)

-- Epoch 1
Norm: 89870.22, NNZs: 3, Bias: -155.051327, T: 200, Avg. loss: 227510618.879137
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 43791.04, NNZs: 3, Bias: -144.898405, T: 400, Avg. loss: 200670830.244106
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 21826.51, NNZs: 3, Bias: -167.580253, T: 600, Avg. loss: 220221238.438343
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 44052.83, NNZs: 3, Bias: -220.577819, T: 800, Avg. loss: 179903697.744537
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 43829.42, NNZs: 3, Bias: -246.905532, T: 1000, Avg. loss: 159178154.202827
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 45138.87, NNZs: 3, Bias: -208.546352, T: 1200, Avg. loss: 142129650.458868
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 27699.02, NNZs: 3, Bias: -168.679560, T: 1400, Avg. loss: 134776289.480256
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 30003.76, NNZs: 3, Bias: -147.095138, T: 1600, Avg. loss: 122695625.336222
Total training time: 0.

SGDClassifier(eta0=0.0001, loss='log', n_jobs=-1, random_state=15, verbose=2)

In [21]:
lr_clsfr.coef_

array([[  3925.14601273, -16033.05764291,  10502.94022174]])

In [22]:
lr_clsfr.intercept_

array([-239.12473731])

## [1.2] SVM(SGDClassifier with hinge)

In [23]:
"""
svm_clsfr: Support Vector Machine classifier
"""
svm_clsfr = linear_model.SGDClassifier(loss='hinge', eta0 = 0.0001, alpha = 0.0001, penalty = 'l2', random_state = 15, verbose = 2, n_jobs = -1 )

In [24]:
svm_clsfr.fit(d_train, y)

-- Epoch 1
Norm: 50970.78, NNZs: 3, Bias: -139.425296, T: 200, Avg. loss: 237646740.055412
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 48251.18, NNZs: 3, Bias: -107.540533, T: 400, Avg. loss: 198997629.606033
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 47283.82, NNZs: 3, Bias: -98.147510, T: 600, Avg. loss: 221678301.804550
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 42763.27, NNZs: 3, Bias: -203.499872, T: 800, Avg. loss: 184224165.832094
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 46523.86, NNZs: 3, Bias: -208.473184, T: 1000, Avg. loss: 163252412.932515
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 19449.28, NNZs: 3, Bias: -203.212119, T: 1200, Avg. loss: 144245644.752882
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 28910.00, NNZs: 3, Bias: -180.696759, T: 1400, Avg. loss: 130092109.903065
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 34971.40, NNZs: 3, Bias: -163.150693, T: 1600, Avg. loss: 121277810.479388
Total training time: 0.0

SGDClassifier(eta0=0.0001, n_jobs=-1, random_state=15, verbose=2)

In [25]:
svm_clsfr.coef_

array([[-1441.65036452, -3083.88512888, 10638.5348658 ]])

In [26]:
svm_clsfr.intercept_

array([-213.74703893])

# [2] Task 2
## [2.1] Logistic regression(SGDClassifier with logloss) after standarization

In [27]:
print("Top {} rows of DataFrame : \n\n{}", [3, data.head(n = 3)])

Top {} rows of DataFrame : 

{} [3,             f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0]


In [29]:
scaler = StandardScaler()

In [30]:
f1_feature_nda = data['f1'].values.reshape(-1, 1)

scaler.fit(f1_feature_nda)
data['f1_transform'] = scaler.transform(f1_feature_nda)

In [31]:

f2_feature_nda = data['f2'].values.reshape(-1, 1)

scaler.fit(f2_feature_nda)
data['f2_transform'] = scaler.transform(f2_feature_nda)

In [32]:
f3_feature_nda = data['f3'].values.reshape(-1, 1)

scaler.fit(f3_feature_nda)
data['f3_transform'] = scaler.transform(f3_feature_nda)

In [33]:
print("Top {} rows of DataFrame : \n\n{}", [3, data.head(n = 3)])

Top {} rows of DataFrame : 

{} [3,             f1            f2        f3    y  f1_transform  f2_transform  \
0  -195.871045 -14843.084171  5.532140  1.0     -0.423126     -1.555602   
1 -1217.183964  -4068.124621  4.416082  1.0     -2.520394     -0.517290   
2     9.138451   4413.412028  0.425317  0.0     -0.002139      0.300020   

   f3_transform  
0      0.181651  
1     -0.200648  
2     -1.567659  ]


In [34]:
d_train_std = data[['f1_transform', 'f2_transform', 'f3_transform']].values
print("1. Data Type of d_train_std: {}", [type(d_train_std)])
print("2. Shape of d_train_std: {}\n\n", [d_train_std.shape])


print("1. Data Type of y: {}", [type(y)])
print("2. Shape of y: ", [y.shape])

1. Data Type of d_train_std: {} [<class 'numpy.ndarray'>]
2. Shape of d_train_std: {}

 [(200, 3)]
1. Data Type of y: {} [<class 'numpy.ndarray'>]
2. Shape of y:  [(200,)]


In [35]:
lr_clsfr.fit(d_train_std, y)

-- Epoch 1
Norm: 53.31, NNZs: 3, Bias: -5.276812, T: 200, Avg. loss: 1.866743
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 47.34, NNZs: 3, Bias: 3.430650, T: 400, Avg. loss: 1.352641
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 43.99, NNZs: 3, Bias: 2.140512, T: 600, Avg. loss: 1.213044
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 33.54, NNZs: 3, Bias: -5.951509, T: 800, Avg. loss: 1.279978
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 32.19, NNZs: 3, Bias: 1.875443, T: 1000, Avg. loss: 0.999923
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 31.45, NNZs: 3, Bias: -0.998614, T: 1200, Avg. loss: 0.563070
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 32.57, NNZs: 3, Bias: 2.720694, T: 1400, Avg. loss: 0.687991
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 30.51, NNZs: 3, Bias: -2.435934, T: 1600, Avg. loss: 0.722018
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 28.04, NNZs: 3, Bias: -3.174216, T: 1800, Avg. loss: 0.807365
Total training ti

SGDClassifier(eta0=0.0001, loss='log', n_jobs=-1, random_state=15, verbose=2)

In [36]:
lr_clsfr.coef_

array([[-0.29741788, -0.66973479, 10.35436789]])

In [37]:
lr_clsfr.intercept_

array([-0.72647926])

## [2.2] SVM(SGDClassifier with hinge)

In [38]:
svm_clsfr.fit(d_train_std, y)

-- Epoch 1
Norm: 42.77, NNZs: 3, Bias: -0.401235, T: 200, Avg. loss: 2.007617
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 41.12, NNZs: 3, Bias: -0.275640, T: 400, Avg. loss: 1.330494
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 34.84, NNZs: 3, Bias: 0.082357, T: 600, Avg. loss: 1.548790
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 33.91, NNZs: 3, Bias: -5.367733, T: 800, Avg. loss: 1.324727
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 33.04, NNZs: 3, Bias: -0.044521, T: 1000, Avg. loss: 0.970131
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 33.35, NNZs: 3, Bias: -4.658497, T: 1200, Avg. loss: 0.786032
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 33.34, NNZs: 3, Bias: 4.123484, T: 1400, Avg. loss: 1.002599
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 35.12, NNZs: 3, Bias: -0.193457, T: 1600, Avg. loss: 0.904594
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 32.42, NNZs: 3, Bias: -3.925287, T: 1800, Avg. loss: 1.007940
Total training 

SGDClassifier(eta0=0.0001, n_jobs=-1, random_state=15, verbose=2)

In [39]:
svm_clsfr.coef_

array([[ 2.23347737,  0.46842383, 22.39791493]])

In [40]:
svm_clsfr.intercept_

array([-0.77415149])