<h1><font color='blue'> 8E and 8F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [2]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, stratify = y)
X_train, X_cv, y_train, y_cv = train_test_split(X_train, y_train, test_size = 0.20, stratify = y_train)

In [3]:
gamma = 0.001
C = 100
clf = SVC(kernel = 'rbf', gamma = gamma, C = C)
clf.fit(X_train, y_train)

def rbf(sv , xq , gamma):
    norm = np.linalg.norm(sv-xq)
    return  np.exp(-gamma *(norm**2))

def decision_function(X_cv , gamma , support_vectors ,dual_coef , intercept):
    decision_vector = []
    for xq in X_cv :
        dec_func = 0
        for sv , dc  in zip(support_vectors , dual_coef[0] ):
            dec_func += (dc * rbf(sv,xq, gamma))
        dec_func += intercept[0]
        decision_vector.append(dec_func)
    return decision_vector

support_vectors = clf.support_vectors_
dual_coef = clf.dual_coef_
intercept = clf.intercept_
f_cv = decision_function(X_cv , gamma , support_vectors ,dual_coef , intercept)
f_cv

[1.8621263408958462,
 -2.0467258866292135,
 -2.3307703084497384,
 -3.929198703006032,
 -1.9276472133667348,
 -3.126805972816593,
 -2.3562595394060204,
 1.3384773673877013,
 -3.8689855327669087,
 -3.4794178142411973,
 -0.2280033143942526,
 -2.383674929830884,
 1.8698881422036542,
 -1.6899883932842337,
 1.8471423450789408,
 -2.0723421506255257,
 -4.079267679040422,
 -3.311368829343872,
 -1.9659390097255973,
 -0.3079889386608081,
 -2.931665169345431,
 1.9366716670379893,
 0.7701649763480609,
 -0.9694239021773208,
 -3.2378592532871218,
 -2.4878617471376665,
 -3.0500316820119857,
 -3.739847040810313,
 -3.1508077001891714,
 -3.275605084983719,
 -0.755489247084109,
 1.216760786553953,
 1.6054304893963312,
 -2.0836414493052,
 -1.8428011103819366,
 -1.2785334017711656,
 -3.5707694996776618,
 3.354877333319242,
 -3.4236433592634605,
 -3.7838805602791674,
 -3.682694148152445,
 -1.623649331383485,
 1.7192228537170613,
 -2.3538088658924132,
 0.2843399258508632,
 -2.437536295524462,
 -3.468655079274

In [4]:
clf.decision_function(X_cv)

array([ 1.86212634, -2.04672589, -2.33077031, -3.9291987 , -1.92764721,
       -3.12680597, -2.35625954,  1.33847737, -3.86898553, -3.47941781,
       -0.22800331, -2.38367493,  1.86988814, -1.68998839,  1.84714235,
       -2.07234215, -4.07926768, -3.31136883, -1.96593901, -0.30798894,
       -2.93166517,  1.93667167,  0.77016498, -0.9694239 , -3.23785925,
       -2.48786175, -3.05003168, -3.73984704, -3.1508077 , -3.27560508,
       -0.75548925,  1.21676079,  1.60543049, -2.08364145, -1.84280111,
       -1.2785334 , -3.5707695 ,  3.35487733, -3.42364336, -3.78388056,
       -3.68269415, -1.62364933,  1.71922285, -2.35380887,  0.28433993,
       -2.4375363 , -3.46865508, -1.9020552 , -1.76715048, -4.32359914,
       -2.13713503, -2.12274111, -3.69112813, -0.41501149, -0.32351837,
       -3.62882553, -3.81231702, -2.92043552, -1.51388306, -2.35703818,
       -4.12014867, -2.8903229 ,  1.60028393, -1.79696972, -2.2036979 ,
       -1.29523096, -2.5559022 ,  0.88145781,  1.76853617, -3.21

### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


<h2><font color='Geen'> 8F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm


In [11]:
from sklearn.linear_model import SGDClassifier

In [6]:
N_pos = []
N_neg = []
for i in y_train:
    if i == 1:
        N_pos.append(i)
    else:
        N_neg.append(i)
N_pos = len(N_pos)
N_neg = len(N_neg)
N_pos, N_neg

(969, 2231)

In [7]:
y_pos = (N_pos + 1)/ (N_pos + 2)
y_pos

0.9989701338825953

In [8]:
y_neg = 1 / (N_neg + 2)
y_neg

0.0004478280340349306

In [9]:
new_y_cv = []
for j in y_cv:
    if j != 1:
        new_y_cv.append(y_neg)
    elif j == 1:
        new_y_cv.append(y_pos)
new_y_cv

[0.9989701338825953,
 0.9989701338825953,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.9989701338825953,
 0.9989701338825953,
 0.0004478280340349306,
 0.9989701338825953,
 0.0004478280340349306,
 0.9989701338825953,
 0.0004478280340349306,
 0.9989701338825953,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.9989701338825953,
 0.9989701338825953,
 0.9989701338825953,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.9989701338825953,
 0.9989701338825953,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.9989701338825953,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.0004478280340349306,
 0.9989701338825953,
 0.0004478

In [13]:
%%time
from tqdm import tqdm
import math
from math import log

def initialize_weights(dim):
    dim = X_train[0] 
    w = np.zeros((1,))
    b = 0
   
    return w,b

dim = X_train[0] 
w,b = initialize_weights(dim)


def sigmoid(z):

    return 1. / (1 + np. exp(-z))

def logloss(y_true,y_pred):
    
    loss = -sum(map(lambda y_true, y_pred: y_true*np.log10(y_pred) + (1-y_true)*np.log10(1-y_pred), y_true, y_pred))/len(y_true)

    return loss

def gradient_dw(x,y,w,b,alpha,N):

    dw = x * (y - sigmoid(np.dot(w, x) + b)) - (alpha / N) * w

    return dw

def gradient_db(x,y,w,b):
    
    db = y - sigmoid(np.dot(w, x) + b)

    return db

log_loss=[]
epoch_list = []
def train(X_train,y_train):

    w,b = initialize_weights(X_train[0])
    eta0 = 0.0001
    
    for e in tqdm(range(epochs)):
        y_tr_pred=[]
        y_ts_pred=[]
        for i in range(len(X_train)):
            
            w = w + (eta0 * gradient_dw(X_train[i], y_train[i], w, b, alpha, N))
            b = b + (eta0 * gradient_db(X_train[i], y_train[i], w, b))

        for k in range(len(X_train)):
            z = np.dot(w,X_train[k])+b
            s = sigmoid(z)
            y_tr_pred.append(s)
        l_tr = logloss(y_train,y_tr_pred)
        log_loss.append(l_tr)


        epoch_list.append(e)
        
    return w,b

Wall time: 9.95 ms


In [14]:
%%time
alpha=0.0001
eta0=0.0001
N=len(f_cv)
epochs=50
w,b=train(f_cv,new_y_cv)

100%|██████████| 50/50 [00:01<00:00, 34.39it/s]

Wall time: 1.46 s


In [15]:
w

array([1.0824396])

In [16]:
b

array([-0.08332192])

In [17]:
f_test = clf.decision_function(X_test)
f_test

array([ 1.10427592e+00, -3.34116354e+00, -1.72577806e+00,  9.79048385e-01,
        5.72444883e-03, -4.37027279e+00, -1.54960311e+00, -4.45912892e+00,
        1.74408753e+00,  1.59726980e+00, -2.12715353e+00, -2.57998206e+00,
       -1.05001415e+00, -1.73500400e+00, -4.18890380e+00, -5.98021692e-01,
       -1.78780878e+00,  1.68394007e+00, -3.08137360e+00,  1.22775917e-01,
       -2.28990708e+00, -2.96502116e+00,  8.84086848e-01, -3.26482436e+00,
       -2.79444740e+00, -2.78959441e+00, -3.61980318e+00, -3.42209275e+00,
       -1.54957689e+00, -2.00184370e+00, -2.40960022e+00,  1.99706213e+00,
       -6.80971850e-01,  1.52754492e+00, -2.91097061e+00,  1.89166215e+00,
        1.94151562e+00, -3.64395438e+00, -7.01203443e-01,  1.68256250e+00,
       -2.47645912e-01, -2.53149322e+00, -1.44087217e+00, -7.48252449e-01,
        3.36475324e-01,  2.56723511e+00, -2.35079311e+00, -2.58772224e+00,
       -2.62669861e+00, -1.67935828e+00,  2.31739276e+00, -2.83618510e+00,
       -8.42766833e-01, -

In [18]:
p = 1 / 1 + np.exp(-((w*f_test)+b))
p  

array([1.32890377e+00, 4.14444588e+01, 8.03834058e+00, 1.37665003e+00,
       2.08017769e+00, 1.24208525e+02, 6.81635451e+00, 1.36647505e+02,
       1.16454890e+00, 1.19289174e+00, 1.18681570e+01, 1.87430994e+01,
       4.38684503e+00, 8.10898130e+00, 1.02246413e+02, 3.07641798e+00,
       8.52715342e+00, 1.17561846e+00, 3.15303944e+01, 1.95163322e+00,
       1.39618189e+01, 2.79175433e+01, 1.41742571e+00, 3.82367841e+01,
       2.33794347e+01, 2.32621824e+01, 5.56823085e+01, 4.51472495e+01,
       6.81618946e+00, 1.04896033e+01, 1.57548025e+01, 1.12513311e+00,
       3.27148277e+00, 1.20801332e+00, 2.63878770e+01, 1.14025570e+00,
       1.13288762e+00, 5.71306744e+01, 3.32177574e+00, 1.17588052e+00,
       2.42103242e+00, 1.78358481e+01, 6.17054974e+00, 3.44308114e+00,
       1.75510966e+00, 1.06750491e+00, 1.48448521e+01, 1.88923805e+01,
       1.96634024e+01, 7.69342581e+00, 1.08846788e+00, 2.44136922e+01,
       3.70625596e+00, 9.19160050e+00, 1.09204217e+00, 1.11084042e+01,
      

# Note: 
##        In the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that